---
version: "3.8"

services:
  bot-girl:
    container_name: bot-girl
    image: quay.ecpdss.net/k_popov/enthusiast_girl:0.0.9
    volumes:
      - ~/.ssh:/root/.ssh:ro
    environment:
      - TELEGRAM_APITOKEN=insertTokenHere

